# Constantes para nomes de tarefas no pipeline

TASK_ENRICH_METADATA = "ENRICH_METADATA"
TASK_ANONYMIZE_TEXT = "ANONYMIZE_TEXT"
TASK_GENERATE_TAGS = "GENERATE_TAGS"
TASK_EMBEDDING_INDEX = "EMBEDDING_INDEX"
