name: Baixar modelo DeepSeek GGUF

on:
  push:
    branches: ["infra/observability-sprint1"]

jobs:
  baixar-e-salvar:
    runs-on: ubuntu-latest
    steps:
      - name: Limpar arquivos antigos
        run: |
          rm -f *.gguf

      - name: Baixar modelo com autenticação
        run: |
          curl -L -o deepseek-coder-1.3b-instruct-q4_k_m.gguf \
            -H "Authorization: Bearer ${{ secrets.HF_TOKEN }}" \
            -H "User-Agent: Mozilla/5.0" \
            "https://huggingface.co/MaziyarPanahi/Phi-3.5-mini-instruct-GGUF/resolve/main/Phi-3.5-mini-instruct.Q4_K_M.gguf"

      - name: Upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: deepseek-coder-1.3b-instruct-q4_k_m
          path: deepseek-coder-1.3b-instruct-q4_k_m.gguf
