name: Baixar modelo DeepSeek GGUF

on:
  push:
    branches: ["infra/observability-sprint1"]

jobs:
  baixar-e-salvar:
    runs-on: ubuntu-latest
    steps:
      - name: Limpar arquivos antigos
        run: |
          rm -f *.gguf

      - name: Baixar modelo com autenticação
        run: |
          curl -L -oGemma-3-Gaia-PT-BR-4b-it_Q8_0.gguf \
            -H "Authorization: Bearer ${{ secrets.HF_TOKEN }}" \
            -H "User-Agent: Mozilla/5.0" \
            "https://huggingface.co/althayr/Gemma-3-Gaia-PT-BR-4b-it-Q8_0-GGUF/resolve/main/Gemma-3-Gaia-PT-BR-4b-it_Q8_0.gguf"

      - name: Upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: Gemma-3-Gaia-PT-BR-4b-it_Q8_0.gguf
          path: Gemma-3-Gaia-PT-BR-4b-it_Q8_0.gguf
