name: Baixar modelo Gemma GGUF
# alteracoes 1
on:
  workflow_dispatch:

jobs:
  baixar-e-salvar:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar modelo do Hugging Face
        run: |
          curl -L -o gemma-4-E4B-it-OBLITERATED-Q4_K_M.gguf "https://huggingface.co/OBLITERATUS/gemma-4-E4B-it-OBLITERATED/resolve/main/gemma-4-E4B-it-OBLITERATED-Q4_K_M.gguf?download=true"

      - name: Upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: gemma-4-E4B-it-OBLITERATED-Q4_K_M
          path: gemma-4-E4B-it-OBLITERATED-Q4_K_M.gguf
