name: Baixar modelo Gemma GGUF
# alteracoes 1
on:
  workflow_dispatch:

jobs:
  baixar-e-salvar:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar modelo do Hugging Face
        run: |
          curl -L -o gemma-3-1b-it-q4_0.gguf "https://huggingface.co/google/gemma-3-1b-it-qat-q4_0-gguf/resolve/main/gemma-3-1b-it-q4_0.gguf"

      - name: Upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: gemma-3-1b-it-q4_0
          path: gemma-3-1b-it-q4_0.gguf
